# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_streak'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'entries'},
        ),
        migrations.AlterField(
            model_name='journal',
            name='view_password',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
